version: '3'

services:
  postgres:
    image: 'postgres:17.3'
    container_name: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4:8.13
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

volumes:
  postgres:
